agents:
  car_0:
    reward:
      type: centerline
      preset: centerline_racing
      overrides:
        centerline:
          vs_weight: 1.0
          vd_weight: 0.01
          d_weight: 0.02
          steer_weight: 0.1
          collision_penalty: -1000.0
          steer_index: 0
