environment:
  map_dir: maps
  map_bundles: auto
  map_split:
    train_ratio: 0.8
    seed: 42
    shuffle: true
  map_cycle: per_episode
  map_pick: random
  num_agents: 2
  lidar_range: 12.0
  lidar_beams: 108
  centerline_autoload: true
  centerline_features: true
  centerline_render: false
  walls_autoload: true
  spawn_policy: centerline_relative
  spawn_centerline:
    mode: random
    avoid_finish: true
    min_progress: 0.05
    max_progress: 0.95
  spawn_offsets:
    s_offset: -1.0
    d_offset: 0.0
    d_max: 1.0
  spawn_target:
    enabled: true
    speed: 0.5
  spawn_ego:
    speed: 0.5
  vehicle_params:
    mu: 1.0489
    C_Sf: 4.718
    C_Sr: 5.4562
    lf: 0.15875
    lr: 0.17145
    h: 0.074
    length: 0.32
    width: 0.225
    m: 3.74
    I: 0.04712
    s_min: -0.46
    s_max: 0.46
    sv_min: -3.2
    sv_max: 3.2
    v_switch: 0.8
    a_max: 2.0
    v_min: -1.0
    v_max: 1.0
