agents:
  car_0:
    observation:
      preset: centerline
      overrides:
        lidar:
          enabled: true
          beams: 1080
          max_range: 10.0
          normalize: true
        ego_state:
          pose: false
          velocity: false
        target_state:
          enabled: false
        relative_pose:
          enabled: false
        speed:
          enabled: true
        prev_action:
          enabled: true
          dim: 2
        normalization:
          enabled: true
          trainable_only: true
